sudo: false
language: node_js
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
jobs:
  include:
    - stage: test
      node_js: v10
      script: 
      - npm run lint
      - npm run test:ci
      - npm run coveralls

    - stage: build
      node_js: v10
      if: branch = master AND type = push
      script: |
        npm run build
        git add -f build/index.js
        if ! git diff --quiet; then
          git config --global user.email "travis@travis-ci.org"
          git config --global user.name "Travis-CI"
          git config credential.helper "store --file=.git/credentials"
          echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
          git commit -m 'build [skip ci]'
          git push origin HEAD:${TRAVIS_BRANCH}
        fi
